version: 1.2.0+{build}
skip_tags: true
image: Visual Studio 2019
install:
  - sh: https://dotnetwebsite.azurewebsites.net/download/dotnet-core/scripts/v1/dotnet-install.sh --version 3.1.100
build_script:
  - cmd: dotnet publish -r win-x64 -c Release /p:PublishSingleFile=true
after_build:
  - cmd: 7z a injector-%APPVEYOR_BUILD_VERSION%-win64.zip .\LICENSE .\README.md .\CHANGELOG.md .\sample-config.ini .\Injector\bin\Release\netcoreapp3.0\win-x64\publish\Injector.exe
artifacts:
  - path: injector-%APPVEYOR_BUILD_VERSION%-win64.zip